version: '3.8'

services:
  web:
    build:
      context: .
    image: cyberprism/file-inclusion
    container_name: cyberprism-file-inclusion-${USER_ID:-default}
    ports:
      - "80"
    environment:
      - FLAG=${FLAG}
    volumes:
      - ./src:/var/www/html
    command: >
      sh -c "echo $${FLAG} > /flag.txt && apache2-foreground"
